# cspell:ignore EDITMSG
ci:
  autoupdate_schedule: weekly

default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-json
      - id: debug-statements
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: fix-byte-order-marker

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v10.0.1
    hooks:
      - id: cspell # Spell check changed files
        args:
          - --no-must-find-files
          - --no-progress
          - --no-summary
          - --show-context
          - --show-suggestions
          - --gitignore
          - --files # this needs to be the last argument so that the paths are passed correctly.
        additional_dependencies: ["@cspell/dict-en-ca"]
      - id: cspell # Spell check the commit message
        name: check commit message spelling
        args:
          - --no-must-find-files
          - --no-progress
          - --no-summary
          - --language-id cpp
          - --files
          - .git/COMMIT_EDITMSG
        stages: [commit-msg]
        always_run: true # This might not be necessary.
        additional_dependencies: ["@cspell/dict-en-ca"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.49.1
    hooks:
      - id: markdownlint
        args: ["--disable", "MD013", "MD024", "MD036", "--"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100"]
