#!/bin/bash

logger -s -p user.info "{robot} {job} using setup file {setup}"
source {setup}

logger -s -p user.info "{robot} {job} launching on interface {interface}"

export ROS_IP=`ifconfig {interface} | grep -o 'inet addr:[^ ]*' | cut -d: -f2`
if [ "$ROS_IP" = "" ]; then
  logger -s -p user.err "{robot} {job} can't run with empty ROS_IP."
  exit 1
fi

export ROS_MASTER_URI={master_uri}
logger -s -p user.info "{robot} {job} launching with ROS_MASTER_URI=$ROS_MASTER_URI"

# Make sure setuidgid is on this system.
which getuidgid
if [ "$?" != "0" ]; then
  logger -s -p user.err "{robot} {job} can't launch as unprivileged user without setuidgid. Please install daemontools package."
  exit 1
fi

# Assemble amalgamated launchfile.
LAUNCH_FILENAME=/tmp/{robot}-{job}.launch
rosrun upstart mklaunch /etc/ros/{rosdistro}/{robot}/{job}.d > $LAUNCH_FILENAME

# Punch it.
export ROS_LOG_DIR=/tmp
setuidgid {user} roslaunch $LAUNCH_FILENAME &
PID=$!

logger -s -p user.info "roslaunch started as background process, PID $PID"
echo "$PID" > /tmp/{robot}-{job}.pid
