#!/usr/bin/env python
from __future__ import print_function

import json
import shlex
import subprocess
from argparse import ArgumentParser

parser = ArgumentParser(description='Process some integers.')
parser.add_argument('interface', help='an integer for the accumulator')

args = parser.parse_args()

cmd = shlex.split("ip -json -4 addr show") + [args.interface]
output = subprocess.check_output(cmd)

# Print the first ip address for this interface
for iface in json.loads(output):
    addr_info = iface['addr_info']
    for addr in addr_info:
        if addr:
            print(addr['local'])
            break
